name : jatin-git-action

on:
 workflow_dispatch:
      inputs:
        int1:
          description: 'Enter first no'     
          required: true
    
        int2:
          description: 'Enter second no'     
          required: true

env:
  a: ${{github.event.inputs.int1}}
  b: ${{github.event.inputs.int1}}

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
  
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run:  |
          cd pythonfile
          python func.py $a $b

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, ubuntu!
  
  # job2:
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.10' 
  #     - run: |
  #         cd pythonfile
  #         python func.py 

      # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, window!
    
